export const API = {
  products: "/products",
  product: (id: string) => `/products/${id}`,
  productInterest: (id: string) => `/products/${id}/interest`,
  productRelated: (id: string) => `/products/${id}/related`,
  productView: (id: string) => `/products/${id}/view`,
  productSearch: "/products/search",
  categoriesTree: "/categories/tree",
  catalogCategories: "/catalog/categories",
  categoryProducts: (slug: string) => `/catalog/categories/${slug}/products`,
  authLogin: "/auth/login",
  authRegister: "/auth/register",
  authRefresh: "/auth/refresh",
  authLogout: "/auth/logout",
  authForgotPassword: "/auth/forgot-password",
  authResetPassword: "/auth/reset-password",
  authMe: "/auth/me",
  customerMe: "/customers/me",
  customerPassword: "/customers/me/password",
  customerAddresses: "/customers/me/addresses",
  customerAddress: (id: string) => `/customers/me/addresses/${id}`,
  customerRecentlyViewed: "/customers/me/recently-viewed",
  cart: "/cart",
  cartItems: "/cart/items",
  cartItem: (id: string) => `/cart/items/${id}`,
  cartMerge: "/cart/merge",
  wishlist: "/wishlist",
  wishlistItem: (productId: string) => `/wishlist/items/${productId}`,
  wishlistMoveToCart: (productId: string) => `/wishlist/items/${productId}/move-to-cart`,
  adminDashboardSummary: "/admin/dashboard/summary",
  adminProducts: "/admin/products",
  adminProduct: (id: string) => `/admin/products/${id}`,
  adminProductStatus: (id: string) => `/admin/products/${id}/status`,
  adminProductsBulkPreview: "/admin/products/bulk/preview",
  adminProductsBulkImport: "/admin/products/bulk/import",
  adminCategories: "/admin/categories",
  adminCategory: (id: string) => `/admin/categories/${id}`,
  adminMediaUpload: "/admin/media/upload",
  adminMediaUploadVideo: "/admin/media/upload-video",
  adminTaxonomyFabrics: "/admin/taxonomy/fabrics",
  adminTaxonomyPrints: "/admin/taxonomy/prints",
  adminTaxonomyFabricsAll: "/admin/taxonomy/fabrics/all",
  adminTaxonomyPrintsAll: "/admin/taxonomy/prints/all",
  adminTaxonomyTagsAll: "/admin/taxonomy/tags/all",
  adminTaxonomyOffersAll: "/admin/taxonomy/offers/all",
  adminTaxonomyFabric: (id: string) => `/admin/taxonomy/fabrics/${id}`,
  adminTaxonomyPrint: (id: string) => `/admin/taxonomy/prints/${id}`,
  adminTaxonomyTag: (id: string) => `/admin/taxonomy/tags/${id}`,
  adminTaxonomyOffer: (id: string) => `/admin/taxonomy/offers/${id}`,
  adminUsers: "/admin/users",
  adminUser: (id: string) => `/admin/users/${id}`,
  adminUserEnabled: (id: string) => `/admin/users/${id}/enabled`,
  adminCarts: "/admin/carts",
  adminCart: (id: string) => `/admin/carts/${id}`,
  adminWishlists: "/admin/wishlists",
  adminWishlist: (id: string) => `/admin/wishlists/${id}`,
  adminCustomers: "/admin/customers",
  adminCustomer: (id: string) => `/admin/customers/${id}`,
  adminInterests: "/admin/interests",
  adminInterestStatus: (id: string) => `/admin/interests/${id}/status`,
  crmLeads: "/crm/leads",
  crmLead: (id: string) => `/crm/leads/${id}`,
  crmLeadStatus: (id: string) => `/crm/leads/${id}/status`,
  policy: (key: string) => `/policies/${key}`,
  promoVideos: "/promo-videos",
  adminPolicies: "/admin/policies",
  adminPolicy: (key: string) => `/admin/policies/${key}`,
  adminPromoVideos: "/admin/promo-videos",
  adminPromoVideo: (id: string) => `/admin/promo-videos/${id}`,
} as const;
