export const API = {
  products: "/products",
  product: (id: string) => `/products/${id}`,
  productInterest: (id: string) => `/products/${id}/interest`,
  productSearch: "/products/search",
  categoriesTree: "/categories/tree",
  catalogCategories: "/catalog/categories",
  categoryProducts: (slug: string) => `/catalog/categories/${slug}/products`,
  authLogin: "/auth/login",
  authMe: "/auth/me",
  adminDashboardSummary: "/admin/dashboard/summary",
  adminProducts: "/admin/products",
  adminProduct: (id: string) => `/admin/products/${id}`,
  adminProductStatus: (id: string) => `/admin/products/${id}/status`,
  adminCategories: "/admin/categories",
  adminCategory: (id: string) => `/admin/categories/${id}`,
  adminMediaUpload: "/admin/media/upload",
  adminTaxonomyFabrics: "/admin/taxonomy/fabrics",
  adminTaxonomyPrints: "/admin/taxonomy/prints",
} as const;
