export const ROUTES = {
  home: "/",
  shop: "/shop",
  about: "/about",
  contact: "/contact",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  wishlist: "/wishlist",
  cart: "/cart",
  account: "/account",
  accountAddresses: "/account/addresses",
  category: (slug: string) => `/category/${slug}`,
  shopNewArrivals: "/shop?sort=new",
  aboutStory: "/about#our-story",
  customStitching: (service?: string) =>
    service ? `/contact?service=${encodeURIComponent(service)}` : "/contact",
  product: (id: string) => `/products/${id}`,
  admin: {
    home: "/admin",
    products: "/admin/products",
    productNew: "/admin/products/new",
    productEdit: (id: string) => `/admin/products/${id}/edit`,
    categories: "/admin/categories",
    users: "/admin/users",
    userDetail: (id: string) => `/admin/users/${id}`,
    customers: "/admin/customers",
    carts: "/admin/carts",
    cartDetail: (id: string) => `/admin/carts/${id}`,
    wishlists: "/admin/wishlists",
    interests: "/admin/interests",
    leads: "/admin/leads",
    taxonomy: "/admin/taxonomy",
  },
} as const;
